### PR TITLE
updating to resolve deprecations for django 1.9 and djangorestframewo…

### PR DESCRIPTION
**Pull request by jdn5126**
…rk 3.3.2 Simple update to use request.data rather than request.DATA to resolve deprecation from djangorestframework 3.3.2. Tested with Django 1.9. Modified urls due to Django 1.8 deprecation warning. Modified migration due to deprecation of South.

### CODE REVIEW

**Comment by jdn5126** [comment]
Forgot to add check to tests/__init__.py for earlier versions of Django. Should call syncdb for pre-1.7 and makemigrations and migrate for post-1.7.

**Comment by sheppard** [comment]
Thanks for the patch!  At this point, I would be fine dropping support for Django 1.7 and earlier entirely, as they aren't [officially supported](https://www.djangoproject.com/download/#supported-versions) by the Django project anymore.

**Comment by jdn5126** [comment]
Any update on this?

**Comment by sheppard** [comment]
Just a couple of things to fix:
 * [ ] Remove Django 1.7 compatibility from `tests/__init__.py`
 * [ ] Update the Travis CI build matrix to test against the latest versions of Django 1.8, Django 1.9, and DRF 3.3 (and no other versions).  Might as well add Python 3.5 while you're at it.
 * [ ] Ensure the tests pass in all environments.

Once you've addressed these I can merge and publish a new release on PyPI.

**Comment by jdn5126** [comment]
Awesome, thank you. Should address all of the environments you want to cover

**Pull request merged**
